"""Pure approved-persona registry and bounded layered context core."""

from .context import (
    AssembledContext,
    CountingContract,
    LayerContext,
    SyntheticTestCounter,
    SyntheticVisibilityPolicy,
    Utf8ByteCounter,
    VisibilityGrant,
    assemble_context,
)
from .registry import ApprovalRequired, ApprovedPersonaRegistry, RegistryAuthority
from .schema import (
    ApprovalBoundaryError,
    ContextBudgetError,
    ContextBudgets,
    ContextItem,
    Facet,
    InputLimitError,
    Layer,
    Omission,
    PersonaProfile,
    PersonaSchemaError,
    SourceRole,
    Trust,
    VersionedFact,
    Visibility,
    provided_item,
    visitor_item,
)

__all__ = [
    "ApprovalBoundaryError",
    "ApprovalRequired",
    "ApprovedPersonaRegistry",
    "AssembledContext",
    "ContextBudgetError",
    "ContextBudgets",
    "ContextItem",
    "CountingContract",
    "Facet",
    "InputLimitError",
    "Layer",
    "LayerContext",
    "Omission",
    "PersonaProfile",
    "PersonaSchemaError",
    "RegistryAuthority",
    "SourceRole",
    "SyntheticTestCounter",
    "SyntheticVisibilityPolicy",
    "Trust",
    "Utf8ByteCounter",
    "VersionedFact",
    "Visibility",
    "VisibilityGrant",
    "assemble_context",
    "provided_item",
    "visitor_item",
]
